### ISSUE TITLE
Puppet 8x support

### ISSUE THREAD

**Issue by flepoutre** [voxpupuli/puppet-augeas#94]
Hi,
Is it possible to fix the module with a new tag for puppet 8x compliant ?

I have tested the module on Puppet 8x and we have this error : 
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Unsupported OS family:  (file: modules/augeas/manifests/params.pp, line: 46, column: 17) on node XXXXXXXXX`

Thanks.

**Comment by absld** [comment]
Hi @flepoutre,

try to enable legacy facts in your Puppet agent's config as a workaround:

/etc/puppetlabs/puppet/puppet.conf:
`[agent]`
`include_legacy_facts = true`

But there's still another problem with the ruby version shipped with Puppet 8:

`/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/augeas.rb:48: warning: undefining the allocator of T_DATA class Augeas`

It's only a warning, so at least no greater problem. Would be nice if this can be fixed though.

**Comment by flepoutre** [comment]
Hello,
Yes ok for the workaround.
On my testing environment I have fixed it with that (please check the screen attachement)
![Capture d’écran 2023-07-04 102644](https://github.com/camptocamp/puppet-augeas/assets/84913246/c60ee745-afb1-4ba0-96de-56d55bc4b769)

**Comment by flepoutre** [comment]
Hi,
Please find an update of the fixes attachment.
Thanks.

![Capture d’écran 2023-07-25 095415](https://github.com/camptocamp/puppet-augeas/assets/84913246/3d92886c-7dc7-47f3-9a9a-27370782ff28)

**Comment by flepoutre** [comment]
Hi,
Any news on this subject ?
Thanks.

**Comment by kenyon** [comment]
Looks like #92 would fix this. Probably better to try to migrate away from this module, like was done in https://github.com/voxpupuli/puppet-postfix/pull/373, for example.

**Comment by jhoblitt** [comment]
Resolved by #99
