### ISSUE TITLE
Migrating this Repository to Vox Pupuli 

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-augeas#96]
Hi Camptocamp Staff,

Voxpupuli is interested in adopting this repository and maintain the software.
@saimonn can you help with this migration?

Kind Regards,
Simon

**Comment by jhoblitt** [comment]
I would like to see this module transfered to vox so we can get the basic plumbing updated.

**Comment by jhoblitt** [comment]
This module is one of the last preventing my production env from migrating to puppet 8. I would volunteer to modernize it if it is transferred to vox. 

/cc @bastelfreak

**Comment by tuxmea** [comment]
Unluckily noone from camptocamp seems to view these repos anymore. Do we somehow have a direct contact to one of the authors with admin privileges?

**Comment by saimonn** [comment]
Hello,

I'm not very vigilant about github notifications, so thanks for waiting until now.

I've initiated the transfer of this repository to voxpupuli, which should be effective in a few minutes.

Thanks all for taking care of all theses puppet modules

**Comment by SimonHoenscheid** [comment]
@saimonn Thanks for migrating this repo!

**Comment by bastelfreak** [comment]
@SimonHoenscheid you asked for the migration, can you also take care of the modulesync + release? The process is documented at https://voxpupuli.org/docs/migrate_module/
